# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.qpid', 'proton-j', '0.31.0')
require_jar('com.microsoft.azure', 'qpid-proton-j-extensions', '1.2.0')
require_jar('org.slf4j', 'slf4j-api', '1.7.25')
require_jar('com.microsoft.azure', 'azure-eventhubs', '2.3.2')
